### ISSUE TITLE
percent_phix on undetermined_percentage_handler.py

### ISSUE THREAD

**Issue by sgaleraalq** [Molmed/checkQC#110]
Good morning.

I am writing this issue because I was trying to implement CheckQC on an preliminary analysis in our company. I experienced that the tool is breaking when trying to find "percent_phix" in our Run information since there are no fields that correlate to this specific matter. When I comment the parts in which "percent_phix" takes part on, the tools finishes correctly.

However, the MultiQC analysis that we run afterwards requires "percent_phix" to be on the output information to correctly assign CheckQC results on their final plots.

I think that the reason why we do not get this "percent_phix" field is because we demultiplex our samples without splitting them by lane (but it is just my guess, I am not completely sure). Could it be possible to implement a new version which it does not really require that field? 

I attach in this issue the parts where I changed your original code and my data so you can work on if you want to.

```
  def compute_threshold(value):
      return value # + mean_phix_per_lane[lane_nbr]

  def create_data_dict(value):
      return {"lane": lane_nbr,
              "percentage_undetermined": percentage_undetermined,
              "threshold": value,
              "computed_threshold": compute_threshold(value)}
              # "phix_on_lane": mean_phix_per_lane[lane_nbr]}
```
[checkqc_trial.zip](https://github.com/Molmed/checkQC/files/13362926/checkqc_trial.zip)

Command I run:
```
checkqc --downgrade-errors UndeterminedPercentageHandler .
```

I also change the config.yaml to:
```
parser_configurations:
  StatsJsonParser:
    # Path to where the bcl2fastq output (i.e. fastq files, etc) is located relative to
    # the runfolder
    bcl2fastq_output_path: Reports/legacy
  SamplesheetParser:
    samplesheet_name: Reports/SampleSheet.csv
```
